version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      frontend:
        patterns: ['*']
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: monthly
    groups:
      backend:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
